language: bash

services:
    - docker

before_install:
    - docker pull koalaman/shellcheck
    - sudo pip install bashate

script:
    - find . -name \*.sh | xargs docker run -t --rm -v $(pwd):/mnt koalaman/shellcheck
    - find . -name \*.sh | xargs bashate

matrix:
    fast_finish: true
