language: bash

services:
    - docker

before_install:
    - docker pull koalaman/shellcheck

script:
    - find . -name \*.sh | xargs docker run -t --rm -v $(pwd):/mnt koalaman/shellcheck

matrix:
    fast_finish: true
